# Build the application from source
FROM golang:1.23 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go clean -modcache && go mod download

COPY ./internal ./internal
COPY ./webapp ./webapp
COPY ./cmd/controller/main.go ./cmd/controller/main.go

RUN go build -o /app/bin/controller ./cmd/controller/main.go

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/controller /controller

EXPOSE 6969

USER nonroot:nonroot

ENTRYPOINT ["/controller"]
