# Build the application from source
FROM golang:1.23 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go clean -modcache && go mod download

COPY ./internal ./internal
COPY ./cmd/agent/main.go ./cmd/agent/main.go

RUN go build -o /app/bin/agent ./cmd/agent/main.go

# Run the tests in the container
FROM build-stage AS run-test-stage
RUN go test -v ./...

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/agent /agent

EXPOSE 4499-4597

USER nonroot:nonroot

ENTRYPOINT ["/agent"]
