services:
  ziti-router-agent:
    container_name: ziti-router-${NODE_NUM}
    image: openziti/ziti-router:1.1.11
    ports:
      - ${ROUTER_PORT}:${ROUTER_PORT}
    environment:
      - ZITI_CTRL_ADVERTISED_ADDRESS=${CONTROLLER_ADDRESS}
      - ZITI_CTRL_ADVERTISED_PORT=1280
      - ZITI_ENROLL_TOKEN=${ROUTER_ENROLLMENT_JWT}
      - ZITI_ROUTER_ADVERTISED_ADDRESS=${ADVERTISED_IP}
      - ZITI_ROUTER_PORT=${ROUTER_PORT}
      - ZITI_ROUTER_MODE=none
      - ZITI_BOOTSTRAP=true
      - ZITI_BOOTSTRAP_CONFIG=true
      - ZITI_BOOTSTRAP_ENROLLMENT=true
      - ZITI_AUTO_RENEW_CERTS=true
      - ZITI_ROUTER_TYPE=edge
    command: run config.yml
    healthcheck:
      test: ziti agent stats
      interval: 3s
      retries: 5
      start_period: 15s
      timeout: 3s
  
  ziti-tunnel-agent:
    container_name: ziti-tunnel-${NODE_NUM}
    image: openziti/ziti-tunnel:1.1.12
    environment:
      - ZITI_ENROLL_TOKEN=${PROMTAIL_JWT}
      - ZITI_IDENTITY_BASENAME=promtail
    networks:
      - net_ziti_promtail
    command: proxy service-loki:3100

  promtail-agent:
    container_name: promtail-${NODE_NUM}
    image: grafana/promtail:3.1.1
    volumes:
      - ../configs/promtail-config-agent.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - net_ziti_promtail
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9080/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      ziti-tunnel-agent:
        condition: service_started
  
  ziti-host-agent:
    container_name: ziti-host-${NODE_NUM}
    image: openziti/ziti-host:1.1.3
    environment:
      - ZITI_ENROLL_TOKEN=${HOST_JWT}
    networks:
      - net_node_exporter
    depends_on:
      ziti-router-agent:
        condition: service_healthy

  node-exporter-agent:
    container_name: node-exporter-${NODE_NUM}
    image: prom/node-exporter:v1.8.2
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - net_node_exporter
    pid: host
  
  dmapz-agent:
    container_name: dmapz-agent-${NODE_NUM}
    image: dmapz-agent:latest
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: host
    command: -jwt ${AGENT_JWT}
    depends_on:
      ziti-router-agent:
        condition: service_healthy
      promtail-agent:
        condition: service_healthy
    user: "${UID}:${GID}"

networks:
  net_ziti_promtail:
    driver: bridge
  net_node_exporter:
    driver: bridge
